import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        brand: {
          "primary": "#2563EB",
          "primary-active": "#1D4ED8",
          "primary-disabled": "#DBEAFE",
          "ink": "#1E293B",
          "body": "#334155",
          "body-strong": "#0F172A",
          "muted": "#64748B",
          "muted-soft": "#94A3B8",
          "hairline": "#DBEAFE",
          "hairline-soft": "#E2E8F0",
          "canvas": "#EFF6FF",
          "surface-soft": "#F1F5F9",
          "surface-card": "#F8FAFC",
          "surface-cream-strong": "#E2E8F0",
          "surface-dark": "#0F172A",
          "surface-dark-elevated": "#1E293B",
          "surface-dark-soft": "#172033",
          "on-primary": "#FFFFFF",
          "on-dark": "#EFF6FF",
          "on-dark-soft": "#a09d96",
          "accent-teal": "#60A5FA",
          "accent-amber": "#F59E0B",
          "success": "#22C55E",
          "warning": "#F59E0B",
          "error": "#EF4444",
        },
      },
      fontFamily: {
        display: ['"Cormorant Garamond"', '"Tiempos Headline"', "Garamond", '"Times New Roman"', "serif"],
        body: ["Inter", "-apple-system", "BlinkMacSystemFont", '"Segoe UI"', "Roboto", "sans-serif"],
        mono: ['"JetBrains Mono"', "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-xl": ["4rem", { lineHeight: "1.05", letterSpacing: "-0.09375em", fontWeight: "400" }],
        "display-lg": ["3rem", { lineHeight: "1.1", letterSpacing: "-0.0625em", fontWeight: "400" }],
        "display-md": ["2.25rem", { lineHeight: "1.15", letterSpacing: "-0.03125em", fontWeight: "400" }],
        "display-sm": ["1.75rem", { lineHeight: "1.2", letterSpacing: "-0.01875em", fontWeight: "400" }],
        "title-lg": ["1.375rem", { lineHeight: "1.3", letterSpacing: "0", fontWeight: "500" }],
        "title-md": ["1.125rem", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
        "title-sm": ["1rem", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
        "body-md": ["1rem", { lineHeight: "1.55", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["0.875rem", { lineHeight: "1.55", letterSpacing: "0", fontWeight: "400" }],
        "caption": ["0.8125rem", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
        "caption-upper": ["0.75rem", { lineHeight: "1.4", letterSpacing: "0.09375em", fontWeight: "500" }],
        "code": ["0.875rem", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "btn": ["0.875rem", { lineHeight: "1", letterSpacing: "0", fontWeight: "500" }],
        "nav-link": ["0.875rem", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
      },
      spacing: {
        "xxs": "0.25rem",
        "xs": "0.5rem",
        "sm": "0.75rem",
        "md": "1rem",
        "lg": "1.5rem",
        "xl": "2rem",
        "xxl": "3rem",
        "section": "6rem",
      },
      borderRadius: {
        "xs": "0.25rem",
        "sm": "0.375rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "pill": "9999px",
      },
      maxWidth: {
        "content": "75rem",
      },
      screens: {
        "mobile": "0px",
        "tablet": "768px",
        "desktop": "1024px",
        "wide": "1440px",
      },
    },
  },
  plugins: [],
};

export default config;
