import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        brand: {
          "primary": "#cc785c",
          "primary-active": "#a9583e",
          "primary-disabled": "#e6dfd8",
          "ink": "#141413",
          "body": "#3d3d3a",
          "body-strong": "#252523",
          "muted": "#6c6a64",
          "muted-soft": "#8e8b82",
          "hairline": "#e6dfd8",
          "hairline-soft": "#ebe6df",
          "canvas": "#faf9f5",
          "surface-soft": "#f5f0e8",
          "surface-card": "#efe9de",
          "surface-cream-strong": "#e8e0d2",
          "surface-dark": "#181715",
          "surface-dark-elevated": "#252320",
          "surface-dark-soft": "#1f1e1b",
          "on-primary": "#ffffff",
          "on-dark": "#faf9f5",
          "on-dark-soft": "#a09d96",
          "accent-teal": "#5db8a6",
          "accent-amber": "#e8a55a",
          "success": "#5db872",
          "warning": "#d4a017",
          "error": "#c64545",
        },
      },
      fontFamily: {
        display: ['"Cormorant Garamond"', '"Tiempos Headline"', "Garamond", '"Times New Roman"', "serif"],
        body: ["Inter", "-apple-system", "BlinkMacSystemFont", '"Segoe UI"', "Roboto", "sans-serif"],
        mono: ['"JetBrains Mono"', "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-xl": ["4rem", { lineHeight: "1.05", letterSpacing: "-0.09375em", fontWeight: "400" }],
        "display-lg": ["3rem", { lineHeight: "1.1", letterSpacing: "-0.0625em", fontWeight: "400" }],
        "display-md": ["2.25rem", { lineHeight: "1.15", letterSpacing: "-0.03125em", fontWeight: "400" }],
        "display-sm": ["1.75rem", { lineHeight: "1.2", letterSpacing: "-0.01875em", fontWeight: "400" }],
        "title-lg": ["1.375rem", { lineHeight: "1.3", letterSpacing: "0", fontWeight: "500" }],
        "title-md": ["1.125rem", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
        "title-sm": ["1rem", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
        "body-md": ["1rem", { lineHeight: "1.55", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["0.875rem", { lineHeight: "1.55", letterSpacing: "0", fontWeight: "400" }],
        "caption": ["0.8125rem", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
        "caption-upper": ["0.75rem", { lineHeight: "1.4", letterSpacing: "0.09375em", fontWeight: "500" }],
        "code": ["0.875rem", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "btn": ["0.875rem", { lineHeight: "1", letterSpacing: "0", fontWeight: "500" }],
        "nav-link": ["0.875rem", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
      },
      spacing: {
        "xxs": "0.25rem",
        "xs": "0.5rem",
        "sm": "0.75rem",
        "md": "1rem",
        "lg": "1.5rem",
        "xl": "2rem",
        "xxl": "3rem",
        "section": "6rem",
      },
      borderRadius: {
        "xs": "0.25rem",
        "sm": "0.375rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "pill": "9999px",
      },
      maxWidth: {
        "content": "75rem",
      },
      screens: {
        "mobile": "0px",
        "tablet": "768px",
        "desktop": "1024px",
        "wide": "1440px",
      },
    },
  },
  plugins: [],
};

export default config;
